// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0wPfMBO57iEuZ2eaSLfYMJvpA5c79vro',
    appId: '1:596915153935:web:f8c0c86e7153d4fabe877a',
    messagingSenderId: '596915153935',
    projectId: 'chatapptask-5f828',
    authDomain: 'chatapptask-5f828.firebaseapp.com',
    storageBucket: 'chatapptask-5f828.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQPmOxKHFgj7u0buA6f7EU8gCOaNOcOtg',
    appId: '1:596915153935:android:5715e48bb4bd0705be877a',
    messagingSenderId: '596915153935',
    projectId: 'chatapptask-5f828',
    storageBucket: 'chatapptask-5f828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_YiDREuZqN2FpqwN9MOie0GqjgTC-yLQ',
    appId: '1:596915153935:ios:46d96df0e6da7013be877a',
    messagingSenderId: '596915153935',
    projectId: 'chatapptask-5f828',
    storageBucket: 'chatapptask-5f828.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_YiDREuZqN2FpqwN9MOie0GqjgTC-yLQ',
    appId: '1:596915153935:ios:46d96df0e6da7013be877a',
    messagingSenderId: '596915153935',
    projectId: 'chatapptask-5f828',
    storageBucket: 'chatapptask-5f828.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0wPfMBO57iEuZ2eaSLfYMJvpA5c79vro',
    appId: '1:596915153935:web:8e939ef2c60824cebe877a',
    messagingSenderId: '596915153935',
    projectId: 'chatapptask-5f828',
    authDomain: 'chatapptask-5f828.firebaseapp.com',
    storageBucket: 'chatapptask-5f828.appspot.com',
  );
}
